### ISSUE TITLE
Catflap without homepod

### ISSUE THREAD

**Issue by NicholasJallan** [rcastberg/sure_petcare#15]
Hello,

I'm interested in sureflap catflap. Do you think a new sureflap catflap can be controlled/parametrized with code based on yours, without ever being connected to their homepod ? (that i would'nt buy)

Thanks in advance

**Comment by rjclocks** [comment]
You could try, but the communication between the catflap and the homepod is almost certainly encrypted. It is a shame, as the data would be useful to get hold of without having to go to their platform to get it. It may be possible to identify what data is being sent, but probably not trivial.

**Comment by rcastberg** [comment]
Outside the scope of this project.
