### ISSUE TITLE
Can't seem to install add on

### ISSUE THREAD

**Issue by omantench** [rcastberg/sure_petcare#18]
Hi there, I'm probably being a donut but I can't seem to add this guthub repository via either HACS or config of the Hassio GUI.

Here is the error log when I try to add it:
20-11-09 15:08:00 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/dc3846f2/repository.json: [Errno 2] No such file or directory: '/data/addons/git/dc3846f2/repository.json'
20-11-09 15:08:00 ERROR (MainThread) [supervisor.store] https://github.com/rcastberg/sure_petcare is not a valid add-on repository. 

Please can you help?

Many thanks,
Ed

**Comment by benleb** [comment]
This repository cannot be installed via HACS or the Supervisor Addons thing afaik...

**Comment by omantench** [comment]
thanks Ben....so it's a git pull and code into configuration.yaml? ie manual

**Comment by benleb** [comment]
Yes, see here https://github.com/rcastberg/sure_petcare/tree/master/home_assistant

just because I am curious... Is there a specific reason you do not simply use the [surepetcare](https://www.home-assistant.io/integrations/surepetcare/) integration in home assistant or do you just don't know about?

**Comment by omantench** [comment]
Hi Ben, thanks again for your help.

i didn't know that there was a surepetcare integration, i will try to add it, thank you

**Comment by rcastberg** [comment]
Alternative soilution provided.
