### ISSUE TITLE
Cat in or out?

### ISSUE THREAD

**Issue by papabak** [rcastberg/sure_petcare#23]
Is it correct that currently it is not possible to show a cat is IN or OUT? If not, please point me to the place where I can suggest this feature. I'm not a very experienced user ... yet.

**Comment by strix-technica** [comment]
That feature was broken by an API change late December 2023.  I hacked a solution, now merged; see PR #22.  Make sure you're using a current version of the API.  If it's not working for you, file a bug report with more detail of what's happening for you.

**Comment by papabak** [comment]
Thanks! I updated the integration and it works (again).



Verzonden vanuit Outlook voor iOS<https://aka.ms/o0ukef>
________________________________
Van: strix-technica ***@***.***>
Verzonden: Friday, July 12, 2024 3:03:30 PM
Aan: rcastberg/sure_petcare ***@***.***>
CC: papabak ***@***.***>; Author ***@***.***>
Onderwerp: Re: [rcastberg/sure_petcare] Cat in or out? (Issue #23)


That feature was broken by an API change late December 2023. I hacked a solution, now merged; see PR #22<https://github.com/rcastberg/sure_petcare/pull/22>. Make sure you're using a current version of the API. If it's not working for you, file a bug report with more detail of what's happening for you.
